version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end
    hostname: front-end
    restart: always
    cap_drop:
      - all
    environment:
      - reschedule=on-node-failure
    links:
      - cart
      - catalogue
    external_links:
      - user
      - orders
  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    hostname: edge-router
    restart: always
    environment:
      - reschedule=on-node-failure
    links:
      - front-end
  catalogue:
    image: weaveworksdemos/catalogue
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - reschedule=on-node-failure
    links:
      - catalogue-db
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  cart:
    image: weaveworksdemos/cart
    hostname: cart
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    environment:
      - reschedule=on-node-failure
    links:
      - cart-db
    mem_limit: 1073741824
  cart-db:
    image: mongo
    hostname: cart-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
      - reschedule=on-node-failure
  # user-sim:
  #   image: weaveworksdemos/load-test
  #   cap_drop:
  #     - all
  #   read_only: true
  #   hostname: user-simulator
  #   command: "-d 60 -r 200 -c 2 -h edge-router"
  #   links:
  #     - edge-router