apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    name: zipkin
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 9411
    targetPort: 9411
  selector:
    name: zipkin


