name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build-test-images:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: 
    strategy:
      matrix:
        repo: ["openapi", "healthcheck"]
    steps:
    - uses: actions/checkout@v2

    #
    #
    # Push to dockerhub
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.repo }}
        push: true
        tags: ${{ env.GROUP }}/${{ matrix.repo }}:${{ github.sha }}
